//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subsidy.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Subsidy2
    {
        [Required]
        public int id { get; set; }
        [Required]
        public string Фамилия_родитель_ { get; set; }
        [Required]
        public string Имя_родитель_ { get; set; }
        [Required]
        public string Отчество_родитель_ { get; set; }
        [Required]
        public string Серия_паспорта_ { get; set; }
        [Required]
        public string Номер_паспотра_ { get; set; }
        [Required]
        public string Тип__паспотр_РФ_Иностранный__ { get; set; }
        [Required]
        public string Фамилия_ребенок_ { get; set; }
        [Required]
        public string Имя_ребенок_ { get; set; }
        [Required]
        public string Отчество_ребенок_ { get; set; }
        [Required]
        public string Серия_свидетельство_о_рожд__ { get; set; }
        [Required]
        public string Номер_свидетельство_о_рожд__ { get; set; }
        [Required]
        public string Тип_РФ_Иностранный_ { get; set; }
        [Required]
        public Nullable<System.DateTime> дата_рождения_ребенок_ { get; set; }
        [Required]
        public string Номер_телефона { get; set; }
        [Required]
        public string Почта { get; set; }
    }
}
